homework08/src/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import NoteViewSet, UserViewSet

app_name = 'api'
router = DefaultRouter(trailing_slash=False)
router.register(r'notes', NoteViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include(router.urls)),
]

homework08/src/notes/urls.py
from django.urls import path
from .views import NoteList, NoteDetail, NoteCreate, NoteUpdate, NoteDelete

app_name = 'notes'

urlpatterns = [
    path('', NoteList.as_view(), name='index'),
    path('<int:pk>/', NoteDetail.as_view(), name='detail'),
    path('new/', NoteCreate.as_view(), name='create'),
    path('<int:pk>/edit/', NoteUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', NoteDelete.as_view(), name='delete'),

]

homework08/src/notes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()


class Note(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    owner = models.ForeignKey(User, related_name='note_owner',
                              on_delete=models.CASCADE, blank=True)
    tags = models.CharField(blank=True, max_length=200)
    access = models.CharField(max_length=200,
                              blank=True)

    def __str__(self):
        return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now

    def tags_as_list(self):
        return self.tags.split(',')

homework08/src/notes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):

    class Meta:

        model = Note
        fields = ['title', 'tags', 'body', 'access']

homework08/src/notes/views.py
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
 ListView, DetailView, CreateView, UpdateView, DeleteView
)

from .models import Note
from .forms import NoteForm
from .mixins import NoteMixin


class NoteList(LoginRequiredMixin, ListView):

    paginate_by = 5
    template_name = 'notes/index.html'
    context_object_name = 'latest_note_list'

    def dispatch(self, *args, **kwargs):
        return super(NoteList, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        if "filter_title" in self.request.GET.keys():
            q = Note.objects.filter(title__contains=self.request.GET['filter_title'])
        elif "filter_tag" in self.request.GET.keys():
            tags = self.request.GET['filter_tag']
            while tags[0] == ' ':
                tags = tags[1:]
            q = Note.objects.filter(tags__contains=tags)
        else:
            q = Note.objects
        return q.filter(access__contains=self.request.user).order_by('-pub_date')


class NoteDetail(LoginRequiredMixin, DetailView):

    model = Note
    template_name = 'notes/detail.html'
    context_object_name = 'note'

    def dispatch(self, *args, **kwargs):
        return super(NoteDetail, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Note.objects.filter(access__contains=self.request.user)


class NoteCreate(LoginRequiredMixin, NoteMixin, CreateView):

    form_class = NoteForm
    template_name = 'notes/form.html'
    success_url = reverse_lazy('notes:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.pub_date = timezone.now()
        if str(self.request.user) not in form.instance.access:
            form.instance.access += ' '
            form.instance.access += str(self.request.user)
        return super(NoteCreate, self).form_valid(form)


class NoteUpdate(LoginRequiredMixin, NoteMixin, UpdateView):

    model = Note
    form_class = NoteForm
    template_name = 'notes/form.html'

    def get_queryset(self):
        return Note.objects.filter(access__contains=self.request.user)

    def get_success_url(self):
        return reverse('notes:update', kwargs={
            'pk': self.object.pk
        })

    def form_valid(self, form):
        if str(self.request.user) not in form.instance.access:
            form.instance.access += ' '
            form.instance.access += str(self.request.user)
        return super(NoteUpdate, self).form_valid(form)


class NoteDelete(LoginRequiredMixin, DeleteView):

    model = Note
    success_url = reverse_lazy('notes:create')

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user)

homework08/src/templates/notes/detail.html
{% extends "base.html" %}

{% block content %}



<h5>{{ note.tags }}</h5>

<h1>{{ note.title }}</h1>

<p>{{ note.body | safe }} </p>

<footer>
Users with access to this note:
    {{ note.access }}
</footer>
{% endblock %}

homework08/src/templates/notes/form.html
{% extends "base.html" %}

{% block extra_head %}
{% load wysiwyg %}
{% wysiwyg_setup %}
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-4">
            <nav id="sidebar">

              <div class="new-note">
                <a href="{% url 'notes:create' %}" class="new-note btn btn-outline-dark">+ New Note</a>
              </div>

              <ul id="notes">
              {% if notes %}
                  {% for note in notes %}
                    <li data-url="{% url 'notes:update' note.id %}">
                        <div class="note-tags ">{{ note.tags }}</div>
                        <div class="note-title">{{ note.title }}</div>
                        <div class="note-body">{{ note.body | safe }}</div>
                    </li>
                  {% endfor %}
                {% else %}
                  <li>No notes are available.</li>
              {% endif %}
              </ul>
            </nav>
        </div>

        <div class="col-8">

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        {% if object %}
        <form action="{% url 'notes:update' object.pk %}" method="post" accept-charset="utf-8">
        {% else %}
        <form action="{% url 'notes:create' %}" method="post" accept-charset="utf-8">
        {% endif %}

            {% csrf_token %}
            {% for field in form %}
            <p>
                {% if field.errors %}
            	<div class="alert alert-danger" role="alert">
                    {{ field.errors }}
            	</div>
                {% endif %}
                {{ field }}
            </p>
            {% endfor %}
            <input type="hidden" name="next" value="{{ next }}" />
        
        <div class="row">
        {% if object %}
            <input class="btn btn-outline-dark" type="submit" value="Update Note"/>
        {% else %}
            <input class="btn btn-outline-dark" type="submit" value="Create Note"/>
        {% endif %}
        
        </form>
        
        {% if object %}
            <form action="{% url 'notes:delete' object.pk %}" method="post">
                {% csrf_token %}
                <button class="btn btn-outline-dark" type='submit'>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </button>
            </form>
        {% endif %}
        </div>

        </div>
    </div>

<script>
    $("#id_tags").attr("placeholder", "type tags separated by ,")
    $("#id_access").attr("placeholder", "emails of users who will have access to this note")
</script>

{% wysiwyg_editor "id_body" %}

{% endblock %}

homework08/src/templates/notes/index.html
{% extends "base.html" %}

{% block content %}

{% if request.GET.msg %}

<div class="row">
  <div class=" alert alert-success" role="alert">
    {{ request.GET.msg }}
  </div>
</div>

{% endif %}

{% if request.GET.filter_title %}
    <div class="row">
      <h4>Search results for: {{request.GET.filter_title}}</h4>
    </div>

{% elif request.GET.filter_tag %}
    <div class="row">
        <h4>Notes with tag: {{request.GET.filter_tag}}</h4>
    </div>
{% endif %}

<div class="row">
    <form action="{% url 'notes:index' %}"class="form-inline" method="GET">
      <input name="filter_title" class="form-control" type="search" placeholder="Search by note's title" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</div>


{% if latest_note_list %}
    <ul>
    {% for note in latest_note_list %}
    <p>
    <div class='row'>
        {% for tag in note.tags_as_list %}
        <form action="{% url 'notes:index' %}" method="GET">
            <input class="btn btn-outline-dark" name="filter_tag" type="submit" value="{{tag}}"/>
        </form>
        {% endfor %}
    </div>
    
    <li><p><a href="{% url 'notes:detail' note.id %}">{{ note.title }}</a></p></li>
        <a href="{% url 'notes:update' note.id %}">Edit</a><br/>
        <p>{{ note.body | safe }}</p>
    </p>
    <hr />
    {% endfor %}
    </ul>
{% else %}
    <p>No notes are available.</p>
{% endif %}

{% if is_paginated %}
<div class="pagination">
   <span class="step-links">
       {% if page_obj.has_previous %}
           <a href="?page={{ page_obj.previous_page_number }}">previous</a>
       {% endif %}

       <span class="current">
           Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
       </span>

       {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
       {% endif %}
  </span>
</div>
{% endif %}

<a href="{% url 'notes:create' %}">Create a new note</a>

{% endblock %}