homework08/src/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import RegisterView, ConfirmView

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(next_page=reverse_lazy('accounts:login')),
         name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm/<str:secret_key>', ConfirmView, name='confirm'),
]

homework08/src/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import NoteViewSet, UserViewSet

app_name = 'api'
router = DefaultRouter(trailing_slash=False)
router.register(r'notes', NoteViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include(router.urls)),
]

homework08/src/templates/base.html
{% load static %}

<html>
  <head>
    <title>Elevennote</title>

    <link rel="stylesheet" media="all" href='{% static "bootstrap/css/bootstrap.css" %}'>
    <link rel="stylesheet" media="all" href='{% static "elevennote/main.css" %}'>
    <link rel="stylesheet" media="all" href='{% static "font-awesome/css/font-awesome.css" %}'>
    <link rel="stylesheet" type="text/css" media="screen"
          href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic|Oxygen:300,400,700" />

    <script src="{% static "elevennote/jquery.js" %}"></script>
    <script src="{% static "elevennote/main.js" %}"></script>

    {% block extra_head %}{% endblock %}
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">ElevenNote</a>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto"></ul>
          <span class="navbar-text">
            Signed in as {{ user.email }}.
            <a href="#">Profile</a> | 
            <a href="{% url 'accounts:logout' %}">Logout</a>
          </span>
        </div>
        {% endif %}
      </nav>

      <main role="main" class="container-fluid mt-4">
        {% block content %}{% endblock %}
      </main>
  </body>
</html>